#!/usr/bin/env python3
"""Generate Orbita from geometry only: no external images, footage, fonts or audio."""
from pathlib import Path
from math import sqrt, sin, cos, pi
import shutil
import subprocess
from PIL import Image, ImageDraw
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen

WIDTH, HEIGHT, CELL, UPM = 96, 54, 32, 2048
FRAME_COUNT = 30
SOURCE = 'Original procedural animation generated by scripts/generate_default_video.py'
CREDIT = 'Orbita. Original Font TV procedural animation. CC0 1.0 Universal.'


def make_frames():
    frames = []
    scale = 4
    for second in range(FRAME_COUNT):
        phase = 2 * pi * second / FRAME_COUNT
        image = Image.new('L', (WIDTH * scale, HEIGHT * scale))
        draw = ImageDraw.Draw(image)
        def ellipse(box, fill=None, outline=None, width=1):
            draw.ellipse(tuple(round(v * scale) for v in box), fill=fill,
                         outline=outline, width=width * scale)
        for i in range(27):
            x, y = (i * 37 + 7) % 96, (i * 19 + 4) % 48
            brightness = round(100 + 80 * (1 + sin(phase + i)) / 2)
            ellipse((x, y, x + .55, y + .55), fill=brightness)
        # Elliptic orbital path, shaded planet and rotating surface bands.
        ellipse((15, 13, 82, 42), outline=70)
        for radius in range(14 * scale, 0, -1):
            r = radius / scale
            brightness = round(60 + 150 * (1 - r / 14))
            ellipse((49-r, 25-r, 49+r, 25+r), fill=brightness)
        for latitude in range(-10, 12, 4):
            half = sqrt(14**2 - latitude**2)
            points = [(round((49 + x) * scale),
                       round((25 + latitude + 1.4 * sin(x / 7 + phase)) * scale))
                      for x in range(-int(half)+1, int(half))]
            draw.line(points, fill=160, width=scale)
        ellipse((35, 11, 63, 39), outline=235)
        x, y = 49 + 33*cos(phase), 27 + 14*sin(phase)
        ellipse((x-2.5, y-2.5, x+2.5, y+2.5), fill=255)
        # Original lunar foreground silhouette, kept visible in the lower half.
        points = [(0,54),(0,49),(10,45),(19,49),(32,44),(43,48),
                  (55,46),(68,50),(83,45),(96,48),(96,54)]
        draw.polygon([(x*scale,y*scale) for x,y in points], fill=55)
        draw.line([(x*scale,y*scale) for x,y in points[1:-1]], fill=145, width=scale)
        image = image.resize((WIDTH, HEIGHT), Image.Resampling.LANCZOS)
        frames.append([min(5, round(value / 51)) for value in image.getdata()])
    return frames


def rect(pen, x0, y0, x1, y1):
    pen.moveTo((x0, y0))
    pen.lineTo((x1, y0))
    pen.lineTo((x1, y1))
    pen.lineTo((x0, y1))
    pen.closePath()


def build(path, frames, part):
    first, last = {'Full': (0, HEIGHT), 'Top': (0, HEIGHT // 2),
                   'Bottom': (HEIGHT // 2, HEIGHT)}[part]
    digits = [f'digit{i}' for i in range(10)]
    names = [f'frame{i:02d}' for i in range(FRAME_COUNT)]
    order = ['.notdef', 'space', 'colon'] + digits + names
    glyphs = {name: TTGlyphPen(None).glyph() for name in order[:3]}
    for index, name in enumerate(names):
        pen = TTGlyphPen(None)
        for y in range(first, last):
            for x in range(WIDTH):
                # Area coverage, rather than side length, encodes luminance.
                side = round(CELL * sqrt(frames[index][y * WIDTH + x] / 5))
                if side:
                    left = x * CELL + (CELL - side) // 2
                    bottom = (last - y - 1) * CELL + (CELL - side) // 2
                    rect(pen, left, bottom, left + side, bottom + side)
        glyphs[name] = pen.glyph()
    for index, name in enumerate(digits):
        glyphs[name] = glyphs[names[index]]
    metrics = {name: (WIDTH * CELL, 0) for name in order}
    metrics['space'] = metrics['colon'] = (0, 0)
    height = (last - first) * CELL
    family = 'Default' + part
    builder = FontBuilder(UPM, isTTF=True)
    builder.setupGlyphOrder(order)
    builder.setupCharacterMap({32: 'space', 58: 'colon', **{
        ord(str(i)): name for i, name in enumerate(digits)}})
    builder.setupGlyf(glyphs)
    # CoreText positions outlines using the side bearing; preserve black pixels
    # at the left edge so separately rendered halves keep the same origin.
    for name in digits + names:
        metrics[name] = (WIDTH * CELL, glyphs[name].xMin)
    builder.setupHorizontalMetrics(metrics)
    builder.setupHorizontalHeader(ascent=height, descent=0, lineGap=0)
    builder.setupNameTable({
        'familyName': family, 'styleName': 'Regular',
        'uniqueFontIdentifier': 'tv_watch.orbita.' + family + '-Regular',
        'fullName': family + ' Regular', 'psName': family + '-Regular',
        'version': 'Version 1.000', 'copyright': CREDIT,
        'description': SOURCE, 'licenseDescription': CREDIT,
        'licenseInfoURL': 'https://creativecommons.org/publicdomain/zero/1.0/',
    })
    builder.setupOS2(sTypoAscender=height, sTypoDescender=0, sTypoLineGap=0,
                     usWinAscent=height, usWinDescent=0)
    builder.setupPost()
    pairs = '\n'.join(f'sub digit{i // 10} digit{i % 10} by frame{i % FRAME_COUNT:02d};'
                      for i in range(60))
    builder.addOpenTypeFeatures('''
        languagesystem DFLT dflt;
        languagesystem latn dflt;
        @images = [%s];
        @clock = [@images colon];
        feature rlig {
            lookup Seconds { %s } Seconds;
            lookup HidePrefix { sub @images' @clock by space; } HidePrefix;
        } rlig;
    ''' % (' '.join(digits + names), pairs))
    builder.save(path)



if __name__ == '__main__':
    frames = make_frames()
    output = Path('out/default')
    output.mkdir(parents=True, exist_ok=True)
    for part in ('Full', 'Top', 'Bottom'):
        path = Path('WatchTV/Shared') / ('Default' + part + '.ttf')
        build(path, frames, part)
        print(path, path.stat().st_size)
    images = [Image.frombytes('L', (WIDTH, HEIGHT), bytes(v * 51 for v in frame)) for frame in frames]
    sheet = Image.new('L', (WIDTH*4*3, HEIGHT*4*4))
    for index, frame in enumerate(images[::3][:12]):
        sheet.paste(frame.resize((WIDTH*4, HEIGHT*4), Image.Resampling.NEAREST),
                    ((index % 3)*WIDTH*4, (index // 3)*HEIGHT*4))
    sheet.save(output/'contact.png')
    subprocess.run([shutil.which('ffmpeg') or '/opt/homebrew/bin/ffmpeg',
        '-hide_banner', '-loglevel', 'error', '-y', '-f', 'rawvideo', '-pixel_format', 'gray',
        '-video_size', '96x54', '-framerate', '1', '-i', 'pipe:0', '-vf', 'scale=960:540:flags=neighbor',
        '-c:v', 'libx264', '-crf', '18', '-pix_fmt', 'yuv420p', '-movflags', '+faststart',
        str(output/'orbita.mp4')], input=bytes(v*51 for frame in frames for v in frame), check=True)
